### PR TITLE
BaSP-MR-114: Redux classes screen

### PR DESCRIPTION
**Pull request by NicolasKler**
Added redux to all methods (get, put, post and get by id) and correct add button position

### CODE REVIEW

**Comment by CavalloFede** [comment]
There is no success message when you delete a class

**Comment by leo-balonchard** [comment]
> There is no success message when you delete a class


Done

**Review by CavalloFede — APPROVED** [review]

**Review by nicosimo8 — APPROVED** [review]
Seems to be fine

**Comment by nicosimo8** [comment]
> 



> Seems to be fine

fix conflicts and let's go :rocket:

**Comment by NicolasKler** [comment]
https://trello.com/c/8YaR5fWb/114-redux-classes-screen

**Review by Micaela-Rossi — COMMENTED** [review]
All seems good, and  working.
I made a [ticket ](https://trello.com/c/Dcee5taA) because it's not equal at the subscription form in the aspect you need to write all the ids for complete it.

**Pull request merged**
