### PR TITLE
BaSP-MR-112: Finish super-admins redux screen

### PR DESCRIPTION
**Pull request by GinoLucci1**
Finished the SuperAdmins part and fixed modals from previous week.

### CODE REVIEW

**Review by NicolasKler — COMMENTED** [review]
When adding or editing a super admin if you fill the field with an invalid string it takes you back to the home page, it should keep you in the page to fix the issue

**Review by nicosimo8 — APPROVED** [review]

**Review by octavi01 — APPROVED** [review]

**Comment by octavi01** [comment]
nice work

**Review by leo-balonchard — APPROVED** [review]
ready to merge

**Review by NicolasKler — APPROVED** [review]
Looks good to me

**Comment by ryaev** [comment]
PR is reviewed and a new related [ticket](https://trello.com/c/AzgUuT8m/129-bug-super-admin-various-errors) is created

**Pull request merged**
