### PR TITLE
BaSP-MR-135: Admin hook forms

### PR DESCRIPTION
**Pull request by Roberto-Orazi**

### CODE REVIEW

**Review by nicosimo8 — APPROVED** [review]
Working well

**Review by Gianluca27 — APPROVED** [review]

**Review by leo-balonchard — APPROVED** [review]
looks good, but it would be better if you can improve the form style!

**Comment by Micaela-Rossi** [comment]
[React hook form Admins](https://trello.com/c/BfbOPZ5u/135-react-hook-form-admins)

**Review by Micaela-Rossi — COMMENTED** [review]
Functionallity it's all okay, i suggest to change the labels of firstName and lastName  from admins/trainers/form to First Name and Last Name.

**Pull request merged**
