### PR TITLE
BaSP-MR-116: Redux Subscriptions Screen.

### PR DESCRIPTION
**Pull request by Gianluca27**
Deleted old logic and added methods through redux.
Added constants.
Added actions.
Added and combined reducers.

### CODE REVIEW

**Review by octavi01 — COMMENTED** [review]
It won't let me add a subscription

**Comment by moradpablo** [comment]
There are many conflicts with the master that should be fixed prior to approval

**Review by NicolasKler — COMMENTED** [review]
Sometimes it doesnt show all the classes id when you edit.
You cannot edit a member.
If you dont change anything in edit it still shows you success modal.

**Review by nicosimo8 — APPROVED** [review]
We'll fix it with react-hook-form

**Review by leo-balonchard — APPROVED** [review]
We'll fix it with react-hook-form

**Comment by ryaev** [comment]
Bugs already [reported](https://trello.com/c/H2Qwv8iP/97-bug-subscription) or in the process of being [resolved](https://trello.com/c/RNAdJIGa/138-react-hook-form-subcriptions) are detected

**Comment by ryaev** [comment]
New [ticket](https://trello.com/c/TClWpdXs/152-bug-super-admin-email-validations-and-span-alert) is charged as a result of what was requested in [ticket](https://trello.com/c/AzgUuT8m/129-bug-super-admin-alert-message-and-validations)

**Pull request merged**
