### PR TITLE
BaSP-MR-131:  Layout styles

### PR DESCRIPTION
**Pull request by moradpablo**
Adding styles from Figma to the main layout

### CODE REVIEW

**Review by NicolasKler — APPROVED** [review]
Looks good to me

**Review by leo-balonchard — APPROVED** [review]
Excellent work pablito! :muscle:

**Review by Gianluca27 — APPROVED** [review]
Nice job!

**Comment by VictoriaNegrotto** [comment]
Great Job Pablo!!

**Comment by IgnacioCanton** [comment]
FIRST TESTING RESULT
Pablo, everything looks good to me. You have made a great work on this PR. Adding styles respecting the Figma design.

Environment: production branch.
QA: Juan Ignacio Canton

Attachments: N/A

**Comment by ryaev** [comment]
Excellent, the required changes in the [ticket](https://trello.com/c/gfkpfATI/108-suggestion-password-show-button-in-forms) were verified

**Pull request merged**
